-- Tabela sugerowanych pieśni dla programów (z modułu Bazy Pieśni → "Do programu" / "Programy")
-- Frontend już z niej czyta (ProgramDetail.jsx → fetchSongSuggestions). Brakowało UI do zapisu,
-- który teraz dodajemy w WorshipModule. Jeśli tabela już istnieje na środowisku, wystarczy że
-- 'CREATE TABLE IF NOT EXISTS' nie zrobi nic.

CREATE TABLE IF NOT EXISTS public.program_song_suggestions (
  id              bigint generated by default as identity primary key,
  program_id      bigint not null references public.programs(id) on delete cascade,
  song_id         bigint not null references public.songs(id) on delete cascade,
  song_key        text,
  note            text,
  sort_order      integer not null default 0,
  created_by_email text,
  created_at      timestamptz not null default now(),
  unique (program_id, song_id)
);

create index if not exists idx_psc_program_id on public.program_song_suggestions(program_id);
create index if not exists idx_psc_song_id    on public.program_song_suggestions(song_id);

-- RLS: wystarczy uwierzytelnione, bo programy i pieśni są już scope'owane na poziomie
-- swoich tabel. Jeśli potrzebujesz twardszego cięcia per kampus, można zrobić policy
-- przez join do public.programs.
alter table public.program_song_suggestions enable row level security;

drop policy if exists "psc_select" on public.program_song_suggestions;
drop policy if exists "psc_insert" on public.program_song_suggestions;
drop policy if exists "psc_update" on public.program_song_suggestions;
drop policy if exists "psc_delete" on public.program_song_suggestions;

create policy "psc_select" on public.program_song_suggestions
  for select to authenticated using (true);

create policy "psc_insert" on public.program_song_suggestions
  for insert to authenticated with check (true);

create policy "psc_update" on public.program_song_suggestions
  for update to authenticated using (true) with check (true);

create policy "psc_delete" on public.program_song_suggestions
  for delete to authenticated using (true);
