-- Add missing columns from schwro backup data

-- SONGS
ALTER TABLE songs ADD COLUMN IF NOT EXISTS author TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS tempo TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS chords TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS lyrics_chords TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS sheet_music_url TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS chord_format TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS meter TEXT;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS chords_bars TEXT;

-- PROGRAMS
ALTER TABLE programs ADD COLUMN IF NOT EXISTS schedule JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS atmosfera_team JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS produkcja JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS scena JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS szkolka JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS zespol JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS teaching JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS custom_mc_schedule JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS custom_mailing_schedule JSONB;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS custom_mail_schedule JSONB;

-- TEACHING_SPEAKERS
ALTER TABLE teaching_speakers ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE teaching_speakers ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE teaching_speakers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE teaching_speakers ADD COLUMN IF NOT EXISTS email TEXT;

-- KIDS_GROUPS
ALTER TABLE kids_groups ADD COLUMN IF NOT EXISTS room TEXT;
ALTER TABLE kids_groups ADD COLUMN IF NOT EXISTS materials JSONB;
ALTER TABLE kids_groups ADD COLUMN IF NOT EXISTS teacher_ids JSONB;

-- TEAM_ROLES
ALTER TABLE team_roles ADD COLUMN IF NOT EXISTS field_key TEXT;
ALTER TABLE team_roles ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;
ALTER TABLE team_roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- WORSHIP_TEAM
ALTER TABLE worship_team ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE worship_team ADD COLUMN IF NOT EXISTS status TEXT;

-- MEDIA_TEAM
ALTER TABLE media_team ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE media_team ADD COLUMN IF NOT EXISTS status TEXT;

-- NOTIFICATIONS
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS body TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS data JSONB;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS read BOOLEAN DEFAULT false;

-- MESSAGES
ALTER TABLE messages ADD COLUMN IF NOT EXISTS reply_to_id UUID;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS forwarded_from UUID;

-- CONVERSATIONS
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS ministry_key TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- TASKS
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS team TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_time TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS end_time TEXT;

-- EVENTS
ALTER TABLE events ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS time TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_time TEXT;

-- TEAM_MEMBER_ROLES
ALTER TABLE team_member_roles ADD COLUMN IF NOT EXISTS member_id INTEGER;

-- SCHEDULE_ASSIGNMENTS
ALTER TABLE schedule_assignments ADD COLUMN IF NOT EXISTS assigned_by_email TEXT;
ALTER TABLE schedule_assignments ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ;
ALTER TABLE schedule_assignments ADD COLUMN IF NOT EXISTS assignment_type TEXT;
ALTER TABLE schedule_assignments ADD COLUMN IF NOT EXISTS role_name TEXT;

-- MLODZIEZOWKA_MEMBERS
ALTER TABLE mlodziezowka_members ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE mlodziezowka_members ADD COLUMN IF NOT EXISTS join_date DATE;
ALTER TABLE mlodziezowka_members ADD COLUMN IF NOT EXISTS birth_date DATE;

-- HOME_GROUPS
ALTER TABLE home_groups ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE home_groups ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE home_groups ADD COLUMN IF NOT EXISTS region TEXT;

-- KIDS_STUDENTS
ALTER TABLE kids_students ADD COLUMN IF NOT EXISTS birth_year INTEGER;
ALTER TABLE kids_students ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE kids_students ADD COLUMN IF NOT EXISTS parent2_name TEXT;
ALTER TABLE kids_students ADD COLUMN IF NOT EXISTS parent2_phone TEXT;
ALTER TABLE kids_students ADD COLUMN IF NOT EXISTS parent2_email TEXT;
ALTER TABLE kids_students ADD COLUMN IF NOT EXISTS emergency_contact TEXT;
ALTER TABLE kids_students ADD COLUMN IF NOT EXISTS can_pickup TEXT[];

-- KIDS_TEACHERS
ALTER TABLE kids_teachers ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE kids_teachers ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- PRAYER_REQUESTS
ALTER TABLE prayer_requests ADD COLUMN IF NOT EXISTS answered_testimony TEXT;
ALTER TABLE prayer_requests ADD COLUMN IF NOT EXISTS answered_at TIMESTAMPTZ;
ALTER TABLE prayer_requests ADD COLUMN IF NOT EXISTS category TEXT;

-- CONVERSATION_PARTICIPANTS
ALTER TABLE conversation_participants ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT false;
ALTER TABLE conversation_participants ADD COLUMN IF NOT EXISTS muted BOOLEAN DEFAULT false;
ALTER TABLE conversation_participants ADD COLUMN IF NOT EXISTS pinned BOOLEAN DEFAULT false;
ALTER TABLE conversation_participants ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE conversation_participants ADD COLUMN IF NOT EXISTS unread_count INTEGER DEFAULT 0;

-- APP_MODULE_TABS
ALTER TABLE app_module_tabs ADD COLUMN IF NOT EXISTS component_type TEXT;
ALTER TABLE app_module_tabs ADD COLUMN IF NOT EXISTS config JSONB;
ALTER TABLE app_module_tabs ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE app_module_tabs ADD COLUMN IF NOT EXISTS requires_permission TEXT;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';
